#\DeclareLyXModule[hereapplies.sty]{Here Applies}
#DescriptionBegin
#A module for cross-linking concepts to their applications.
#See the hereapplies.sty LaTeX package for more information.
#DescriptionEnd
#Authors: madmurphy

Format 66

AddToPreamble
	\usepackage{hereapplies}
EndPreamble

InsetLayout Flex:Here_applies
	LyXType		custom
	Decoration	Classic
	Font
		Family		Typewriter
		Color		black
		Size		Small
	EndFont
	LabelFont
		Family		Serif
		Color		teal
		Size		Small
	EndFont
	LabelString	"Here applies"
	LatexType	command
	LatexName	hereapplies
	Requires	hereapplies
	ForcePlain	1
	MultiPar	0
	NoInsetLayout	1
	BgColor		lightgray
	Argument 1
		Decoration	Classic
		Font
			Color		blue
		EndFont
		LabelString	"Label"
		MenuString	"Instance label"
		Tooltip		"A string that will become the label for this point of the document (which can be referenced with \ref, \pageref, etc.)"
		Mandatory	0
	EndArgument
End

InsetLayout Flex:Here_applies*
	LyXType		custom
	Decoration	Classic
	Font
		Family		Typewriter
		Color		black
		Size		Small
	EndFont
	LabelFont
		Family		Serif
		Color		teal
		Size		Small
	EndFont
	LabelString	"Here applies*"
	LatexType	command
	LatexName	hereapplies*
	Requires	hereapplies
	ForcePlain	1
	MultiPar	0
	NoInsetLayout	1
	BgColor		lightgray
	Argument 1
		Decoration	Classic
		Font
			Color		blue
		EndFont
		LabelString	"Label"
		MenuString	"Instance label"
		Tooltip		"A string that will become the label for this point of the document (which can be referenced with \ref, \pageref, etc.)"
		Mandatory	0
	EndArgument
End

InsetLayout Flex:Where_applies
	LyXType		custom
	Decoration	Classic
	Font
		Family		Typewriter
		Color		black
		Size		Small
	EndFont
	LabelFont
		Family		Serif
		Color		purple
		Size		Small
	EndFont
	LabelString	"Applications of"
	LatexType	command
	LatexName	whereapplies
	Requires	hereapplies
	ForcePlain	1
	MultiPar	0
	NoInsetLayout	1
	BgColor		lightgray
End

InsetLayout Flex:Where_applies*
	LyXType		custom
	Decoration	Classic
	Font
		Family		Typewriter
		Color		black
		Size		Small
	EndFont
	LabelFont
		Family		Serif
		Color		purple
		Size		Small
	EndFont
	LabelString	"Applications of*"
	LatexType	command
	LatexName	whereapplies*
	Requires	hereapplies
	ForcePlain	1
	MultiPar	0
	NoInsetLayout	1
	BgColor		lightgray
End

